# Generated by Django 5.0.4 on 2024-06-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0001_initial'),
        ('product', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.product'),
        ),
    ]
