# Generated by Django 5.0.4 on 2024-06-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('PDF', 'PDF')], default='Image', max_length=10)),
                ('size', models.IntegerField()),
                ('dimension', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='product.product')),
            ],
        ),
    ]
