# Generated by Django 5.0.4 on 2024-06-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='active',
            new_name='status',
        ),
    ]
