# Generated by Django 5.0.4 on 2024-05-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_role_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='users',
            new_name='user',
        ),
    ]
