# Generated by Django 5.0.4 on 2024-05-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_rename_users_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
