# Generated by Django 5.0.4 on 2024-05-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('roles', '0005_remove_role_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='permission.permission'),
        ),
    ]
