# Generated by Django 5.0.4 on 2024-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_remove_role_user'),
        ('user', '0004_remove_client_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='roles',
            field=models.ManyToManyField(to='roles.role'),
        ),
    ]
